<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PeriodicoPlantilla;
use Illuminate\Support\Str;

class PeriodicoPlantillasSeeder extends Seeder
{
    /**
     * Configuración de retícula fija para todas las plantillas factory.
     */
    private array $configuracion = [
        'columns'         => 5,
        'column_width_px' => 144,
        'gutter_px'       => 4,
        'margin_px'       => 12,
        'page_width_px'   => 720,
        'page_height_px'  => 1040,
    ];

    public function run(): void
    {
        foreach ($this->plantillas() as $data) {
            PeriodicoPlantilla::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }

    // -------------------------------------------------------------------------
    // Definición de plantillas
    // -------------------------------------------------------------------------

    private function plantillas(): array
    {
        return [
            $this->portadaDefault(),
            $this->editorialDefault(),
            $this->politicaA(),
            $this->politicaB(),
            $this->santacruzA(),
            $this->santacruzB(),
            $this->paisA(),
            $this->paisB(),
            $this->economiaA(),
            $this->economiaB(),
            $this->seguridadDefault(),
            $this->mundoDefault(),
        ];
    }

    // -------------------------------------------------------------------------
    // 1. Portada
    // -------------------------------------------------------------------------

    private function portadaDefault(): array
    {
        return [
            'id'           => 'tpl-portada-default',
            'nombre'       => 'Portada — Clásica',
            'slug'         => 'portada-default',
            'categoria'    => 'portada',
            'descripcion'  => 'Portada estándar con masthead, imagen hero, artículo principal y pie publicitario.',
            'preview_color' => '#0B1F3A',
            'is_custom'    => false,
            'configuracion' => $this->configuracion,
            'frames'       => [
                [
                    'id'          => 'f-portada-masthead',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 80,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 48,
                    'color'       => '#0B1F3A',
                ],
                [
                    'id'          => 'f-portada-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 80,
                    'w'           => 432,
                    'h'           => 380,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-portada-hero-lateral',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 80,
                    'w'           => 288,
                    'h'           => 380,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-portada-titular',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 460,
                    'w'           => 432,
                    'h'           => 200,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 14,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-portada-secundario',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 460,
                    'w'           => 288,
                    'h'           => 200,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-portada-sumario',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 660,
                    'w'           => 720,
                    'h'           => 320,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-portada-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 5,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 2. Editorial / Opinión
    // -------------------------------------------------------------------------

    private function editorialDefault(): array
    {
        return [
            'id'            => 'tpl-editorial-default',
            'nombre'        => 'Editorial / Opinión',
            'slug'          => 'editorial-default',
            'categoria'     => 'editorial',
            'descripcion'   => 'Página de editorial con cabecera, artículo editorial en columnas 1-2.5 y artículo de opinión en columnas 2.5-5.',
            'preview_color' => '#D71920',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-editorial-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#0B1F3A',
                ],
                // Editorial: columnas 1-2.5 (x=0, w=360)
                [
                    'id'          => 'f-editorial-articulo',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 360,
                    'h'           => 900,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                // Opinión: columnas 2.5-5 (x=360, w=360)
                [
                    'id'          => 'f-editorial-opinion',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 60,
                    'w'           => 360,
                    'h'           => 500,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-editorial-foto-columnista',
                    'type'        => 'image',
                    'x'           => 360,
                    'y'           => 560,
                    'w'           => 360,
                    'h'           => 340,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-editorial-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 960,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 5,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 3. Política A
    // -------------------------------------------------------------------------

    private function politicaA(): array
    {
        return [
            'id'            => 'tpl-politica-a',
            'nombre'        => 'Política — Variante A',
            'slug'          => 'politica-a',
            'categoria'     => 'politica',
            'descripcion'   => 'Página de política con artículo principal + imagen y dos artículos secundarios.',
            'preview_color' => '#0B1F3A',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-pol-a-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#0B1F3A',
                ],
                [
                    'id'          => 'f-pol-a-hero-img',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 432,
                    'h'           => 300,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-pol-a-principal',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 360,
                    'w'           => 432,
                    'h'           => 280,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 13,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-a-lateral',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 60,
                    'w'           => 288,
                    'h'           => 580,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-a-secundario-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 640,
                    'w'           => 360,
                    'h'           => 220,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-a-secundario-2',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 640,
                    'w'           => 360,
                    'h'           => 220,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-a-breve',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 860,
                    'w'           => 720,
                    'h'           => 120,
                    'z'           => 5,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-a-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 6,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 4. Política B
    // -------------------------------------------------------------------------

    private function politicaB(): array
    {
        return [
            'id'            => 'tpl-politica-b',
            'nombre'        => 'Política — Variante B',
            'slug'          => 'politica-b',
            'categoria'     => 'politica',
            'descripcion'   => 'Variante de política con tres artículos en columnas iguales.',
            'preview_color' => '#1A3560',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-pol-b-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#0B1F3A',
                ],
                [
                    'id'          => 'f-pol-b-img-principal',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 720,
                    'h'           => 260,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-pol-b-art-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 320,
                    'w'           => 240,
                    'h'           => 420,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-b-art-2',
                    'type'        => 'article',
                    'x'           => 240,
                    'y'           => 320,
                    'w'           => 240,
                    'h'           => 420,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-b-art-3',
                    'type'        => 'article',
                    'x'           => 480,
                    'y'           => 320,
                    'w'           => 240,
                    'h'           => 420,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-b-breve',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 740,
                    'w'           => 720,
                    'h'           => 240,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pol-b-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 5,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 5. Santa Cruz A
    // -------------------------------------------------------------------------

    private function santacruzA(): array
    {
        return [
            'id'            => 'tpl-santacruz-a',
            'nombre'        => 'Santa Cruz — Variante A',
            'slug'          => 'santacruz-a',
            'categoria'     => 'santacruz',
            'descripcion'   => 'Página Santa Cruz con artículo principal, imagen lateral y dos artículos secundarios.',
            'preview_color' => '#2E7D32',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-sc-a-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#2E7D32',
                ],
                [
                    'id'          => 'f-sc-a-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 432,
                    'h'           => 300,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-sc-a-principal',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 360,
                    'w'           => 432,
                    'h'           => 300,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 13,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-a-lateral',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 60,
                    'w'           => 288,
                    'h'           => 600,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-a-sec-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-a-sec-2',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-a-breves',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 860,
                    'w'           => 720,
                    'h'           => 120,
                    'z'           => 5,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-a-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 6,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 6. Santa Cruz B
    // -------------------------------------------------------------------------

    private function santacruzB(): array
    {
        return [
            'id'            => 'tpl-santacruz-b',
            'nombre'        => 'Santa Cruz — Variante B',
            'slug'          => 'santacruz-b',
            'categoria'     => 'santacruz',
            'descripcion'   => 'Variante B Santa Cruz con imagen superior completa y tres columnas.',
            'preview_color' => '#388E3C',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-sc-b-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#2E7D32',
                ],
                [
                    'id'          => 'f-sc-b-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 720,
                    'h'           => 280,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-sc-b-art-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 340,
                    'w'           => 240,
                    'h'           => 400,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-b-art-2',
                    'type'        => 'article',
                    'x'           => 240,
                    'y'           => 340,
                    'w'           => 240,
                    'h'           => 400,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-b-art-3',
                    'type'        => 'article',
                    'x'           => 480,
                    'y'           => 340,
                    'w'           => 240,
                    'h'           => 400,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-b-breves',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 740,
                    'w'           => 720,
                    'h'           => 240,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-sc-b-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 5,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 7. País A
    // -------------------------------------------------------------------------

    private function paisA(): array
    {
        return [
            'id'            => 'tpl-pais-a',
            'nombre'        => 'País — Variante A',
            'slug'          => 'pais-a',
            'categoria'     => 'pais',
            'descripcion'   => 'Página País con artículo principal e imagen destacada en columna izquierda.',
            'preview_color' => '#1565C0',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-pais-a-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#1565C0',
                ],
                [
                    'id'          => 'f-pais-a-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 432,
                    'h'           => 280,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-pais-a-principal',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 340,
                    'w'           => 432,
                    'h'           => 320,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 13,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-a-lateral',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 60,
                    'w'           => 288,
                    'h'           => 600,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-a-sec-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-a-sec-2',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-a-breves',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 860,
                    'w'           => 720,
                    'h'           => 120,
                    'z'           => 5,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-a-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 6,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 8. País B
    // -------------------------------------------------------------------------

    private function paisB(): array
    {
        return [
            'id'            => 'tpl-pais-b',
            'nombre'        => 'País — Variante B',
            'slug'          => 'pais-b',
            'categoria'     => 'pais',
            'descripcion'   => 'Variante B País con imagen superior completa y espacio publicitario lateral.',
            'preview_color' => '#1976D2',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-pais-b-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#1565C0',
                ],
                [
                    'id'          => 'f-pais-b-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 720,
                    'h'           => 260,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-pais-b-art-izq',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 320,
                    'w'           => 432,
                    'h'           => 400,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 13,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-b-ad-b1',
                    'type'        => 'ad',
                    'x'           => 432,
                    'y'           => 320,
                    'w'           => 288,
                    'h'           => 400,
                    'z'           => 3,
                    'content'     => '',
                    'format_code' => 'D1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
                [
                    'id'          => 'f-pais-b-sec-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 720,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-b-sec-2',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 720,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-pais-b-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 5,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 9. Economía A
    // -------------------------------------------------------------------------

    private function economiaA(): array
    {
        return [
            'id'            => 'tpl-economia-a',
            'nombre'        => 'Economía — Variante A',
            'slug'          => 'economia-a',
            'categoria'     => 'economia',
            'descripcion'   => 'Página Economía con artículo principal, gráfico/imagen y dos artículos secundarios.',
            'preview_color' => '#E65100',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-eco-a-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#E65100',
                ],
                [
                    'id'          => 'f-eco-a-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 432,
                    'h'           => 260,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-eco-a-principal',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 320,
                    'w'           => 432,
                    'h'           => 340,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 13,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-a-lateral',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 60,
                    'w'           => 288,
                    'h'           => 600,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-a-sec-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-a-sec-2',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-a-breves',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 860,
                    'w'           => 720,
                    'h'           => 120,
                    'z'           => 5,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-a-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 6,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 10. Economía B
    // -------------------------------------------------------------------------

    private function economiaB(): array
    {
        return [
            'id'            => 'tpl-economia-b',
            'nombre'        => 'Economía — Variante B',
            'slug'          => 'economia-b',
            'categoria'     => 'economia',
            'descripcion'   => 'Variante B Economía con tres artículos en columnas iguales y espacio publicitario.',
            'preview_color' => '#F57C00',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-eco-b-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#E65100',
                ],
                [
                    'id'          => 'f-eco-b-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 720,
                    'h'           => 240,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-eco-b-art-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 300,
                    'w'           => 240,
                    'h'           => 380,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-b-art-2',
                    'type'        => 'article',
                    'x'           => 240,
                    'y'           => 300,
                    'w'           => 240,
                    'h'           => 380,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-b-art-3',
                    'type'        => 'article',
                    'x'           => 480,
                    'y'           => 300,
                    'w'           => 240,
                    'h'           => 380,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-b-ad-e1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 680,
                    'w'           => 360,
                    'h'           => 240,
                    'z'           => 4,
                    'content'     => '',
                    'format_code' => 'E1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
                [
                    'id'          => 'f-eco-b-breves',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 680,
                    'w'           => 360,
                    'h'           => 240,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-eco-b-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 5,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 11. Seguridad / Judicial
    // -------------------------------------------------------------------------

    private function seguridadDefault(): array
    {
        return [
            'id'            => 'tpl-seguridad-default',
            'nombre'        => 'Seguridad / Judicial',
            'slug'          => 'seguridad-default',
            'categoria'     => 'seguridad',
            'descripcion'   => 'Página Seguridad/Judicial con artículo principal, imagen y artículos secundarios.',
            'preview_color' => '#B71C1C',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-seg-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#B71C1C',
                ],
                [
                    'id'          => 'f-seg-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 720,
                    'h'           => 280,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-seg-principal',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 340,
                    'w'           => 432,
                    'h'           => 320,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 13,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-seg-lateral',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 340,
                    'w'           => 288,
                    'h'           => 320,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-seg-sec-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-seg-sec-2',
                    'type'        => 'article',
                    'x'           => 360,
                    'y'           => 660,
                    'w'           => 360,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-seg-breves',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 860,
                    'w'           => 720,
                    'h'           => 120,
                    'z'           => 5,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-seg-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 6,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // 12. Mundo / Deportes / Cultura
    // -------------------------------------------------------------------------

    private function mundoDefault(): array
    {
        return [
            'id'            => 'tpl-mundo-default',
            'nombre'        => 'Mundo / Deportes / Cultura',
            'slug'          => 'mundo-default',
            'categoria'     => 'mundo',
            'descripcion'   => 'Página Mundo/Deportes/Cultura con artículo principal, imagen y sección de breves.',
            'preview_color' => '#4A148C',
            'is_custom'     => false,
            'configuracion' => $this->configuracion,
            'frames'        => [
                [
                    'id'          => 'f-mundo-header',
                    'type'        => 'header',
                    'x'           => 0,
                    'y'           => 0,
                    'w'           => 720,
                    'h'           => 60,
                    'z'           => 1,
                    'content'     => '',
                    'font_family' => 'Bebas Neue',
                    'font_size'   => 36,
                    'color'       => '#4A148C',
                ],
                [
                    'id'          => 'f-mundo-hero',
                    'type'        => 'image',
                    'x'           => 0,
                    'y'           => 60,
                    'w'           => 432,
                    'h'           => 280,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-mundo-principal',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 340,
                    'w'           => 432,
                    'h'           => 320,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 13,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-mundo-lateral-1',
                    'type'        => 'article',
                    'x'           => 432,
                    'y'           => 60,
                    'w'           => 288,
                    'h'           => 300,
                    'z'           => 2,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 12,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-mundo-lateral-img',
                    'type'        => 'image',
                    'x'           => 432,
                    'y'           => 360,
                    'w'           => 288,
                    'h'           => 300,
                    'z'           => 3,
                    'content'     => '',
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => null,
                ],
                [
                    'id'          => 'f-mundo-sec-1',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 660,
                    'w'           => 240,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-mundo-sec-2',
                    'type'        => 'article',
                    'x'           => 240,
                    'y'           => 660,
                    'w'           => 240,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-mundo-sec-3',
                    'type'        => 'article',
                    'x'           => 480,
                    'y'           => 660,
                    'w'           => 240,
                    'h'           => 200,
                    'z'           => 4,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 11,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-mundo-breves',
                    'type'        => 'article',
                    'x'           => 0,
                    'y'           => 860,
                    'w'           => 720,
                    'h'           => 120,
                    'z'           => 5,
                    'content'     => '',
                    'font_family' => 'Montserrat',
                    'font_size'   => 10,
                    'color'       => '#000000',
                ],
                [
                    'id'          => 'f-mundo-ad-f1',
                    'type'        => 'ad',
                    'x'           => 0,
                    'y'           => 980,
                    'w'           => 720,
                    'h'           => 55,
                    'z'           => 6,
                    'content'     => '',
                    'format_code' => 'F1',
                    'status'      => 'disponible',
                    'resizable'   => false,
                    'font_family' => null,
                    'font_size'   => null,
                    'color'       => '#E8F0FE',
                ],
            ],
        ];
    }
}
